name: PR-comment
on:
  workflow_run:
    workflows: [PR]
    types: [completed]

jobs:
  artifacts-url-comments:
    name: Add artifact link to PR and related issue
    runs-on: ubuntu-latest
    steps:
      - name: Add artifact links to pull request and related issues step
        uses: tonyhallett/artifacts-url-comments@v1.1.0
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            prefix: "Here is the build that addresses the issue:"
            suffix: "Please try it and let us know if the issue is resolved."
            format: name
            addTo: pullandissues
