name: PR
on:
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:        
      - name: Build addon
        uses: blenderkit/blender-addon-build@main
        with:
          name: sample-addon
          exclude-files: ".git;.github;README.md"
