# Simple build example which runs on every PR and every merge to main branch.
# Can be also triggered manually.

name: simple_build
on:
  pull_request:
    branches: [ '**' ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:        
      - name: Build addon
        uses: blenderkit/blender-addon-build@main
        with:
          name: sample-addon
          exclude-files: ".git;.github;README.md"
